# Generated by Django 2.0.3 on 2018-03-22 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mumber', models.IntegerField(max_length=3)),
                ('category', models.IntegerField(max_length=2)),
                ('begin_date', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Дата заезда')),
                ('end_date', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Дата отъезда')),
                ('cost', models.IntegerField(max_length=5)),
                ('sum', models.IntegerField(max_length=6)),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
