# Generated by Django 2.0.3 on 2018-03-22 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180322_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='category',
            field=models.IntegerField(verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='home',
            name='cost',
            field=models.IntegerField(blank=True, default=0, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='home',
            name='mumber',
            field=models.IntegerField(verbose_name='Номер дома'),
        ),
        migrations.AlterField(
            model_name='home',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Заказчик'),
        ),
        migrations.AlterField(
            model_name='home',
            name='sum',
            field=models.IntegerField(blank=True, default=0, verbose_name='Сумма:'),
        ),
    ]
