# Generated by Django 2.0.3 on 2018-03-22 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20180322_1240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home',
            old_name='mumber',
            new_name='number',
        ),
        migrations.AlterField(
            model_name='home',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=50, verbose_name='Заказчик'),
        ),
    ]
