# Generated by Django 2.0.3 on 2018-03-22 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20180322_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='begin_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Дата заезда'),
        ),
        migrations.AlterField(
            model_name='home',
            name='end_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Дата отъезда'),
        ),
    ]
