# Generated by Django 2.0.3 on 2018-03-22 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20180322_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='free',
            field=models.BooleanField(default=True, verbose_name='Cdj,jlyj'),
        ),
    ]
