# Generated by Django 2.0.3 on 2018-03-23 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_home_free'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat', models.IntegerField(verbose_name='Категория')),
                ('cost', models.IntegerField(blank=True, default=0, verbose_name='Цена')),
            ],
        ),
        migrations.RemoveField(
            model_name='home',
            name='category',
        ),
        migrations.RemoveField(
            model_name='home',
            name='cost',
        ),
        migrations.AlterField(
            model_name='home',
            name='free',
            field=models.BooleanField(default=True, verbose_name='Cвободно'),
        ),
    ]
