# Generated by Django 2.0.3 on 2018-03-23 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20180323_0745'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='Category',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='cat',
            field=models.IntegerField(default=1, verbose_name='Категория'),
        ),
    ]
